ci: verify docker container startup (#6)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,6 +58,15 @@ jobs:
       - name: Run Docker container
         run: docker run -d -e BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} --name prof_bot profticket_bot_image python3 main.py
 
+      - name: Check container logs
+        run: |
+          sleep 5
+          docker logs prof_bot
+          if [ "$(docker inspect -f '{{.State.Running}}' prof_bot)" != "true" ]; then
+            echo "Container failed to start" >&2
+            exit 1
+          fi
+
   build-push:
     runs-on: ubuntu-latest
     needs: build-test
